// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9qli46D7oAQ2JtQ3x62JKEdnDDH-m4e0',
    appId: '1:862959251334:web:816f3b01107c42090bc607',
    messagingSenderId: '862959251334',
    projectId: 'hungrybuddy-c6557',
    authDomain: 'hungrybuddy-c6557.firebaseapp.com',
    storageBucket: 'hungrybuddy-c6557.appspot.com',
    measurementId: 'G-KK01YFDC79',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwtPTy9O6qNVugucjesO4gO1WEYk6fUxo',
    appId: '1:862959251334:ios:9ebf4b6a5b2e99190bc607',
    messagingSenderId: '862959251334',
    projectId: 'hungrybuddy-c6557',
    storageBucket: 'hungrybuddy-c6557.appspot.com',
    iosBundleId: 'com.example.hungryBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9qli46D7oAQ2JtQ3x62JKEdnDDH-m4e0',
    appId: '1:862959251334:web:f5d01b1f2ef8ccdb0bc607',
    messagingSenderId: '862959251334',
    projectId: 'hungrybuddy-c6557',
    authDomain: 'hungrybuddy-c6557.firebaseapp.com',
    storageBucket: 'hungrybuddy-c6557.appspot.com',
    measurementId: 'G-3046JJC0PM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwtPTy9O6qNVugucjesO4gO1WEYk6fUxo',
    appId: '1:862959251334:ios:9ebf4b6a5b2e99190bc607',
    messagingSenderId: '862959251334',
    projectId: 'hungrybuddy-c6557',
    storageBucket: 'hungrybuddy-c6557.appspot.com',
    iosBundleId: 'com.example.hungryBuddy',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXA1FhX6o4G6owiI_YnX4AT1J-Y9xVsr4',
    appId: '1:862959251334:android:86b0e7cdc4b105cb0bc607',
    messagingSenderId: '862959251334',
    projectId: 'hungrybuddy-c6557',
    storageBucket: 'hungrybuddy-c6557.appspot.com',
  );

}